# permissions for end users to edit microapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microapplication-editor-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - microapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - microapplications/status
  verbs:
  - get
