# permissions for end users to view microapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microapplication-viewer-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - microapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - microapplications/status
  verbs:
  - get
